"""YT link added to films

Revision ID: 99941fc3f0cd
Revises: b1ea71a790d9
Create Date: 2023-02-03 20:20:09.634956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99941fc3f0cd'
down_revision = 'b1ea71a790d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube', sa.Text(), nullable=True))
        batch_op.drop_column('youtube_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_link', sa.INTEGER(), nullable=True))
        batch_op.drop_column('youtube')

    # ### end Alembic commands ###
