"""start

Revision ID: c69d3355e395
Revises: 79ed9538a4ad
Create Date: 2023-01-31 14:09:31.559469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69d3355e395'
down_revision = '79ed9538a4ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acteur',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voornaam', sa.Text(), nullable=True),
    sa.Column('achternaam', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titel', sa.Text(), nullable=True),
    sa.Column('jaartal', sa.Integer(), nullable=True),
    sa.Column('regisseur_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regisseur',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('voornaam', sa.Text(), nullable=True),
    sa.Column('achternaam', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rol',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acteur_id', sa.Integer(), nullable=True),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('personage', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol')
    op.drop_table('regisseur')
    op.drop_table('film')
    op.drop_table('acteur')
    # ### end Alembic commands ###
