"""Added Wiki to Film

Revision ID: 13f95545a544
Revises: b0e4354003e1
Create Date: 2023-01-30 10:48:56.969248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f95545a544'
down_revision = 'b0e4354003e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wiki', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('wiki')

    # ### end Alembic commands ###
